### ISSUE TITLE
Getting error "unable to convert 10.16 to a codename"

### ISSUE THREAD

**Issue by xyzwilliamxyz** [pedrovgs/Shot#255]
Hi,

when Karumi Shot is trying to save screenshots on MAC OS  11.5.2, I'm getting this error `unable to convert 10.16 to a codename`.

Any idea of what it could be?

Thanks

**Comment by pedrovgs** [comment]
First time I see this error @xyzwilliamxyz could you please provide a sample project reproducing the error?

**Comment by walve03** [comment]
Hi @pedrovgs, thanks for the reply. I think this issue was related to something in the current state of the OS which was not working properly with some other library used under Shot (I saw this message in other places through the internet). After formating the OS, it started working again. I think we can close this issue.

**Comment by xyzwilliamxyz** [comment]
Hi @pedrovgs, thanks for the reply. I think this issue was related to something in the current state of the OS which was not working properly with some other library used under Shot (I saw this message in other places through the internet). After formating the OS, it started working again. I think we can close this issue.

**Comment by pedrovgs** [comment]
Ok, thanks for the info @xyzwilliamxyz
