### ISSUE TITLE
Please consider transferring ownership to the community

### ISSUE THREAD

**Issue by MyDogTom** [pedrovgs/Shot#340]
Hi @pedrovgs ,

I believe that this project is being used by a significant number of people. Unfortunately, there has been a lack of support and involvement from the maintainers. Two crucial pull requests have been open for over a year: PR #292 and PR #283.

Would you consider transferring ownership to the community? For instance, the [MobileNativeFoundation](https://github.com/MobileNativeFoundation) could be a suitable organization to take over.

You can find more information about the benefits of moving projects to the MNF at [Benefits of moving projects to the MNF](https://github.com/MobileNativeFoundation/foundation/blob/main/moving-project-benefits.md) and learn about the project lifecycle at [Project Lifecycle](https://github.com/MobileNativeFoundation/foundation/blob/main/project-lifecycle.md).

**Comment by pedrovgs** [comment]
Hi @MyDogTom I think this is not an option. Just to give you an example, from the 2 PRs you mention, [one](https://github.com/pedrovgs/Shot/pull/283) is not a solution for the problem the contributor was facing, and [the other one](https://github.com/pedrovgs/Shot/pull/292) broke the build as the CI report shows. If you check [the other PR open](https://github.com/pedrovgs/Shot/pull/333), the same thing happens, CI is not passing.

I'm not actively implementing features and fixes or updates for this project because I'm not working on Android apps right now. I've been working on this for years, but this is not the case anymore. Even when I'm not working on Android apps right now, I've been reviewing the PRs and answering issues. Not as active as I've been doing it for the 5 previous years, but I've been working on it. Just remember all the contributors here (I'm including you as a contributor here) don't work for this project and is something we do after work during nights and weekends, so reviewing and development pace is not going to be the same as you'd expect from a company.

If you or any other collaborator would like to contribute I'm more than happy to give you access to this repository, but I'm afraid I'm not going to transfer ownership to the MNF or any other foundation. If we get some active contributors I'll create its own organization, but I'll not transfer it to any org created already by other devs. If there are no contributors that would like to join the project, companies or other organizations are always allowed to fork this project and continue working on it as I've been doing for years for free 😃
